name: mustache
version: 0.2.5

author: Greg Lowe <greg@vis.net.nz>
description: Mustache template library
homepage: https://github.com/xxgreg/mustache

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  reflectable: '^2.0.0'

dev_dependencies:
  test: any

  build_runner: ^0.8.0
  build_test: ^0.10.0
  build_web_compilers: ^0.4.0
