name: 'mustache_reflection_test'

version: 0.0.1
description: An absolute bare-bones web app.
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:

  mustache:
    path: ../../../

dev_dependencies:

  build_runner: ^0.8.0
  build_test: ^0.10.0
  build_web_compilers: ^0.4.0


